select 
    timestamp_created
    ,key_primary_waitlist_id
    ,intake_date
    ,intake_case_manager
    ,outcome_status
    ,outcome_outcome
    ,outcome_date_inactive
    ,outcome_case_manager
    ,gen_unit_size
    ,income_monthly
    ,income_source
    ,intake_client_phone_numbers
    ,intake_client_mailing_address
    ,intake_client_city
    ,intake_client_state
    ,intake_client_zip
    ,gen_family_size
    ,gen_family_type
from
    Waitlist
where
    Waitlist.intake_date >= '10/01/2017'